### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [robinwhittleton/henryk-sienkiewicz_with-fire-and-sword_jeremiah-curtin#1]
**chapter-56.xhtml**

- [ ]  I think an em-dash would be more correct than a two-em-dash because the dialog is interrupted ([SEMOS 8.7.7.7.2](https://standardebooks.org/manual/1.6.2/single-page#8.7.7.7.2)).
`<p>“May the wolves tear this hor⁠⸺”</p>` --> `<p>“May the wolves tear this hor⁠—”</p>`

**chapter-60.xhtml**

- [ ] Again, the dialog is interrupted.
`A scream of “Lor⁠⸺!” smothered`... --> `A scream of “Lor⁠—!” smothered`...

**Comment by robinwhittleton** [comment]
Ah, but these are partially obscured words (as per [8.7.7.8.4](https://standardebooks.org/manual/1.6.2/single-page#8.7.7.8.4)). @acabal: what would we do in the case that a word is partially obscured and interrupts dialogue?

**Comment by acabal** [comment]
Interrupted speech gets an em dash. The 1st example looks like interrupted speech to me unless there's other context here that I don't know.

Iis the 2nd example a name that is obscured elsewhere in the book? If not then it's just interrupted speech. If it *is* obscured elsewhere, then the person is just shouting a name which happens to be obscured to us so it would be a two em dash.

**Comment by robinwhittleton** [comment]
OK, single-em dashes it is :) Updated in https://github.com/robinwhittleton/henryk-sienkiewicz_with-fire-and-sword_jeremiah-curtin/commit/cd87f8eaef6588299f064d4fbc8d8da88b4a36fe.

**Comment by acabal** [comment]
Probably a good clarification to make in the manual, interrupted vs obscured speech
